// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TRACECOMPILERTESTERBASIC_20011112_TRACEDEFINITIONS_H__
#define __TRACECOMPILERTESTERBASIC_20011112_TRACEDEFINITIONS_H__

#define AUTOGEN_TRACES_HAVE_FIXED_IDS
#include <isi_macros.h>

#undef TRACECOMPILERTESTERBASIC_COMPONENT
#define TRACECOMPILERTESTERBASIC_COMPONENT 0x20011112
#undef INCLUDED_NON_SOURCE_FILE_TEST
#define INCLUDED_NON_SOURCE_FILE_TEST 0xde
#undef NON_SOURCE_FILE_TRACE1
#define NON_SOURCE_FILE_TRACE1 0x1
#undef NON_SOURCE_FILE_TRACE2
#define NON_SOURCE_FILE_TRACE2 0x2
#undef BASIC_OK_TEST
#define BASIC_OK_TEST 0xdf
#undef TEST_BASIC_INT8
#define TEST_BASIC_INT8 0x1
#undef TEST_BASIC_INT16
#define TEST_BASIC_INT16 0x2
#undef TEST_BASIC_INT32
#define TEST_BASIC_INT32 0x3
#undef TEST_BASIC_INT64
#define TEST_BASIC_INT64 0x4
#undef TEST_BASIC_UINT8
#define TEST_BASIC_UINT8 0x5
#undef TEST_BASIC_UINT16
#define TEST_BASIC_UINT16 0x6
#undef TEST_BASIC_UINT32
#define TEST_BASIC_UINT32 0x7
#undef TEST_BASIC_UINT64
#define TEST_BASIC_UINT64 0x8
#undef TEST_BASIC_HEX8
#define TEST_BASIC_HEX8 0x9
#undef TEST_BASIC_HEX16
#define TEST_BASIC_HEX16 0xa
#undef TEST_BASIC_HEX32
#define TEST_BASIC_HEX32 0xb
#undef TEST_BASIC_HEX64
#define TEST_BASIC_HEX64 0xc
#undef TEST_BASIC_STRING8
#define TEST_BASIC_STRING8 0xd
#undef TEST_BASIC_STRING16
#define TEST_BASIC_STRING16 0xe
#undef TEST_BASIC_FFIX
#define TEST_BASIC_FFIX 0xf
#undef TEST_BASIC_FEXP
#define TEST_BASIC_FEXP 0x10
#undef TEST_BASIC_FOPT
#define TEST_BASIC_FOPT 0x11
#undef ARRAY_OK_TEST
#define ARRAY_OK_TEST 0xe0
#undef TEST_ARRAY_INT8
#define TEST_ARRAY_INT8 0x1
#undef TEST_ARRAY_INT16
#define TEST_ARRAY_INT16 0x2
#undef TEST_ARRAY_INT32
#define TEST_ARRAY_INT32 0x3
#undef TEST_ARRAY_INT64
#define TEST_ARRAY_INT64 0x4
#undef TEST_ARRAY_UINT8
#define TEST_ARRAY_UINT8 0x5
#undef TEST_ARRAY_UINT16
#define TEST_ARRAY_UINT16 0x6
#undef TEST_ARRAY_UINT32
#define TEST_ARRAY_UINT32 0x7
#undef TEST_ARRAY_UINT64
#define TEST_ARRAY_UINT64 0x8
#undef TEST_ARRAY_HEX8
#define TEST_ARRAY_HEX8 0x9
#undef TEST_ARRAY_HEX16
#define TEST_ARRAY_HEX16 0xa
#undef TEST_ARRAY_HEX32
#define TEST_ARRAY_HEX32 0xb
#undef TEST_ARRAY_HEX64
#define TEST_ARRAY_HEX64 0xc
#undef TEST_ARRAY_FFIX
#define TEST_ARRAY_FFIX 0xd
#undef TEST_ARRAY_FEXP
#define TEST_ARRAY_FEXP 0xe
#undef TEST_ARRAY_FOPT
#define TEST_ARRAY_FOPT 0xf
#undef BASIC_TWO_SIMILAR_OK_TEST
#define BASIC_TWO_SIMILAR_OK_TEST 0xe1
#undef TEST_BASIC_SIMILAR2_INT8
#define TEST_BASIC_SIMILAR2_INT8 0x1
#undef TEST_BASIC_SIMILAR2_INT16
#define TEST_BASIC_SIMILAR2_INT16 0x2
#undef TEST_BASIC_SIMILAR2_INT32
#define TEST_BASIC_SIMILAR2_INT32 0x3
#undef TEST_BASIC_SIMILAR2_INT64
#define TEST_BASIC_SIMILAR2_INT64 0x4
#undef TEST_BASIC_SIMILAR2_UINT8
#define TEST_BASIC_SIMILAR2_UINT8 0x5
#undef TEST_BASIC_SIMILAR2_UINT16
#define TEST_BASIC_SIMILAR2_UINT16 0x6
#undef TEST_BASIC_SIMILAR2_UINT32
#define TEST_BASIC_SIMILAR2_UINT32 0x7
#undef TEST_BASIC_SIMILAR2_UINT64
#define TEST_BASIC_SIMILAR2_UINT64 0x8
#undef TEST_BASIC_SIMILAR2_HEX8
#define TEST_BASIC_SIMILAR2_HEX8 0x9
#undef TEST_BASIC_SIMILAR2_HEX16
#define TEST_BASIC_SIMILAR2_HEX16 0xa
#undef TEST_BASIC_SIMILAR2_HEX32
#define TEST_BASIC_SIMILAR2_HEX32 0xb
#undef TEST_BASIC_SIMILAR2_HEX64
#define TEST_BASIC_SIMILAR2_HEX64 0xc
#undef TEST_BASIC_SIMILAR2_STRING8
#define TEST_BASIC_SIMILAR2_STRING8 0xd
#undef TEST_BASIC_SIMILAR2_FFIX
#define TEST_BASIC_SIMILAR2_FFIX 0xe
#undef TEST_BASIC_SIMILAR2_FEXP
#define TEST_BASIC_SIMILAR2_FEXP 0xf
#undef TEST_BASIC_SIMILAR2_FOPT
#define TEST_BASIC_SIMILAR2_FOPT 0x10
#undef ARRAY_TWO_SIMILAR_OK_TEST
#define ARRAY_TWO_SIMILAR_OK_TEST 0xe2
#undef TEST_ARRAY_SIMILAR2_INT8
#define TEST_ARRAY_SIMILAR2_INT8 0x1
#undef TEST_ARRAY_SIMILAR2_INT16
#define TEST_ARRAY_SIMILAR2_INT16 0x2
#undef TEST_ARRAY_SIMILAR2_INT32
#define TEST_ARRAY_SIMILAR2_INT32 0x3
#undef TEST_ARRAY_SIMILAR2_INT64
#define TEST_ARRAY_SIMILAR2_INT64 0x4
#undef TEST_ARRAY_SIMILAR2_UINT8
#define TEST_ARRAY_SIMILAR2_UINT8 0x5
#undef TEST_ARRAY_SIMILAR2_UINT16
#define TEST_ARRAY_SIMILAR2_UINT16 0x6
#undef TEST_ARRAY_SIMILAR2_UINT32
#define TEST_ARRAY_SIMILAR2_UINT32 0x7
#undef TEST_ARRAY_SIMILAR2_UINT64
#define TEST_ARRAY_SIMILAR2_UINT64 0x8
#undef TEST_ARRAY_SIMILAR2_HEX8
#define TEST_ARRAY_SIMILAR2_HEX8 0x9
#undef TEST_ARRAY_SIMILAR2_HEX16
#define TEST_ARRAY_SIMILAR2_HEX16 0xa
#undef TEST_ARRAY_SIMILAR2_HEX32
#define TEST_ARRAY_SIMILAR2_HEX32 0xb
#undef TEST_ARRAY_SIMILAR2_HEX64
#define TEST_ARRAY_SIMILAR2_HEX64 0xc
#undef TEST_ARRAY_SIMILAR2_FFIX
#define TEST_ARRAY_SIMILAR2_FFIX 0xd
#undef TEST_ARRAY_SIMILAR2_FEXP
#define TEST_ARRAY_SIMILAR2_FEXP 0xe
#undef TEST_ARRAY_SIMILAR2_FOPT
#define TEST_ARRAY_SIMILAR2_FOPT 0xf
#undef ENUM_OK_TEST
#define ENUM_OK_TEST 0xe3
#undef TEST_ENUM_OK
#define TEST_ENUM_OK 0x1
#undef TEST_ENUM_ARRAY_OK
#define TEST_ENUM_ARRAY_OK 0x2
#undef TRACE_PERFORMANCE
#define TRACE_PERFORMANCE 0x8b
#undef EVENT_MY_EVENT_TRACE1_START
#define EVENT_MY_EVENT_TRACE1_START 0x1
#undef EVENT_MY_EVENT_TRACE1_STOP
#define EVENT_MY_EVENT_TRACE1_STOP 0x2
#undef EVENT_MY_EVENT_TRACE2_START
#define EVENT_MY_EVENT_TRACE2_START 0x3
#undef EVENT_MY_EVENT_TRACE2_STOP
#define EVENT_MY_EVENT_TRACE2_STOP 0x4
#undef TRACE_FLOW
#define TRACE_FLOW 0x8a
#undef DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY
#define DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY 0x1
#undef DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT
#define DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT 0x2
#undef KEKKONEN
#define KEKKONEN 0xe4
#undef TEXT1
#define TEXT1 0x1
#undef TEXT2
#define TEXT2 0x2
#undef TEXT3
#define TEXT3 0x3
#undef TEXT4
#define TEXT4 0x4
#undef TEXT5
#define TEXT5 0x5
#undef TEXT6
#define TEXT6 0x6
#undef TEXT7
#define TEXT7 0x7
#undef TEXT8
#define TEXT8 0x8
#undef TEXT9
#define TEXT9 0x9
#undef TEXT10
#define TEXT10 0xa
#undef TEXT11
#define TEXT11 0xb
#undef TEXT12
#define TEXT12 0xc
#undef TEXT13
#define TEXT13 0xd
#undef TEXT14
#define TEXT14 0xe
#undef TEXT15
#define TEXT15 0xf
#undef TEXT16
#define TEXT16 0x10
#undef TEXT17
#define TEXT17 0x11
#undef TEXT18
#define TEXT18 0x12
#undef TEXT19
#define TEXT19 0x13
#undef TEXT20
#define TEXT20 0x14
#undef TEXT21
#define TEXT21 0x15
#undef TEXT22
#define TEXT22 0x16
#undef TEXT23
#define TEXT23 0x17
#undef TEXT24
#define TEXT24 0x18
#undef TEXT25
#define TEXT25 0x19
#undef TEXT26
#define TEXT26 0x1a
#undef TEXT27
#define TEXT27 0x1b
#undef TEXT28
#define TEXT28 0x1c
#undef TEXT29
#define TEXT29 0x1d
#undef TEXT30
#define TEXT30 0x1e
#undef TEXT31
#define TEXT31 0x1f
#undef TEXT32
#define TEXT32 0x20
#undef TEXT33
#define TEXT33 0x21
#undef TEXT34
#define TEXT34 0x22
#undef TEXT35
#define TEXT35 0x23
#undef TEXT36
#define TEXT36 0x24
#undef TEXT37
#define TEXT37 0x25
#undef TEXT38
#define TEXT38 0x26
#undef TEXT39
#define TEXT39 0x27
#undef TEXT40
#define TEXT40 0x28
#undef TEXT41
#define TEXT41 0x29
#undef TEXT42
#define TEXT42 0x2a
#undef TEXT43
#define TEXT43 0x2b
#undef TEXT44
#define TEXT44 0x2c
#undef TEXT45
#define TEXT45 0x2d
#undef TEXT46
#define TEXT46 0x2e
#undef TEXT47
#define TEXT47 0x2f
#undef TEXT48
#define TEXT48 0x30
#undef TEXT49
#define TEXT49 0x31

RES_BEGIN( RESOURCE_TRC_SYMBIAN, TRACECOMPILERTESTERBASIC_COMPONENT, TRACECOMPILERTESTERBASIC_TRACE, "TRACECOMPILERTESTERBASIC", "", FALSE )
	
	#include <SharedTraceDefinitions.h>
	
	CONST_TBL_BEGIN( TErrorCodes, 32, SYMBIAN_ENDIANESS, "", "" )
		CONST_TBL_ENTRY( KErrGeneral, -2, "" )
		CONST_TBL_ENTRY( ValueOne, 1, "" )
	CONST_TBL_END
	SEQ_BEGIN( TErrorCodes_Seq, DONT_CREATE_STRUCT, "", "" )
		VALUE_CONST( data, "data", TErrorCodes )
	SEQ_END
	
	TRACE_GROUP_BEGIN( INCLUDED_NON_SOURCE_FILE_TEST, "TraceCompilerTesterBasic: INCLUDED_NON_SOURCE_FILE_TEST: ", ON )
		
		TRACE_BEGIN( NON_SOURCE_FILE_TRACE1, "Inline function GetBigValue1000 return value:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
		TRACE_END()
		
		TRACE_BEGIN( NON_SOURCE_FILE_TRACE2, "Inline function GetBigValue1000 return value:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( BASIC_OK_TEST, "TraceCompilerTesterBasic: BASIC_OK_TEST: ", ON )
		
		TRACE_BEGIN( TEST_BASIC_INT8, "int8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -8, BE, arg1, "arg1", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_INT16, "int16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -16, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_INT32, "int32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_INT64, "int64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_SDEC, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_UINT8, "uint8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg1, "arg1", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_UINT16, "uint16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_UINT32, "uint32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_UINT64, "uint64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_UDEC, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_HEX8, "hex8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg1, "arg1", HEX )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_HEX16, "hex16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg1, "arg1", HEX )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_HEX32, "hex32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", HEX )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_HEX64, "hex64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_STRING8, "ascii:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, STR8, "STR8", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_STRING16, "unicode:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_UNICODE_ZERO_TERMINATED, SYMBIAN_ENDIANESS, unicodePtr, "unicodePtr", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_FFIX, "ffix:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_FEXP, "fexp:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_FOPT, "fopt:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( ARRAY_OK_TEST, "TraceCompilerTesterBasic: ARRAY_OK_TEST: ", ON )
		
		TRACE_BEGIN( TEST_ARRAY_INT8, "int8 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_SDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_INT16, "int16 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_SDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_INT32, "int32 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_SDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_INT64, "int64 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_SDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_UINT8, "uint8 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_UDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_UINT16, "uint16 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_UDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_UINT32, "uint32 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_UDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_UINT64, "uint64 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_UDEC, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_HEX8, "hex8 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_HEX16, "hex16 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_HEX32, "hex32 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_HEX64, "hex64 array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_FFIX, "ffix array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_FEXP, "fexp array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_FOPT, "fopt array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( BASIC_TWO_SIMILAR_OK_TEST, "TraceCompilerTesterBasic: BASIC_TWO_SIMILAR_OK_TEST: ", ON )
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_INT8, "int8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -8, BE, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -8, BE, arg2, "arg2", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_INT16, "int16: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -16, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -16, SYMBIAN_ENDIANESS, arg2, "arg2", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_INT32, "int32: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, arg2, "arg2", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_INT64, "int64: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_SDEC, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_SDEC, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_UINT8, "uint8: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg2, "arg2", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_UINT16, "uint16: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg2, "arg2", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_UINT32, "uint32: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg2, "arg2", DEC )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_UINT64, "uint64: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_UDEC, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_UDEC, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_HEX8, "hex8: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg1, "arg1", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, arg2, "arg2", HEX )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_HEX16, "hex16: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg1, "arg1", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 16, SYMBIAN_ENDIANESS, arg2, "arg2", HEX )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_HEX32, "hex32: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg2, "arg2", HEX )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_HEX64, "hex64: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_STRING8, "ascii: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, STR8len, "STR8_len", STR8_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, STR8, "STR8", STR8_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, STR82len, "STR82_len", STR82_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, STR82, "STR82", STR82_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_FFIX, "ffix: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_FEXP, "fexp: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_BASIC_SIMILAR2_FOPT, "fopt: ," )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg1, "arg1", TRACE_SEQ_QWORD_HEX, 1 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF( arg2, "arg2", TRACE_SEQ_QWORD_HEX, 1 )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( ARRAY_TWO_SIMILAR_OK_TEST, "TraceCompilerTesterBasic: ARRAY_TWO_SIMILAR_OK_TEST: ", ON )
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_INT8, "int8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf8len, "buf8_len", buf8_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_SDEC, buf8_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf82len, "buf82_len", buf82_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf82, "buf82", TRACE_SEQ_BYTE_SDEC, buf82_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_INT16, "int16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf16len, "buf16_len", buf16_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_SDEC, buf16_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf162len, "buf162_len", buf162_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf162, "buf162", TRACE_SEQ_WORD_SDEC, buf162_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_INT32, "int32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf32len, "buf32_len", buf32_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_SDEC, buf32_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf322len, "buf322_len", buf322_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf322, "buf322", TRACE_SEQ_DWORD_SDEC, buf322_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_INT64, "int64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf64len, "buf64_len", buf64_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_SDEC, buf64_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf642len, "buf642_len", buf642_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf642, "buf642", TRACE_SEQ_QWORD_SDEC, buf642_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_UINT8, "uint8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf8len, "buf8_len", buf8_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_UDEC, buf8_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf82len, "buf82_len", buf82_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf82, "buf82", TRACE_SEQ_BYTE_UDEC, buf82_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_UINT16, "uint16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf16len, "buf16_len", buf16_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_UDEC, buf16_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf162len, "buf162_len", buf162_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf162, "buf162", TRACE_SEQ_WORD_UDEC, buf162_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_UINT32, "uint32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf32len, "buf32_len", buf32_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_UDEC, buf32_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf322len, "buf322_len", buf322_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf322, "buf322", TRACE_SEQ_DWORD_UDEC, buf322_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_UINT64, "uint64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf64len, "buf64_len", buf64_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_UDEC, buf64_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf642len, "buf642_len", buf642_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf642, "buf642", TRACE_SEQ_QWORD_UDEC, buf642_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_HEX8, "hex8:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf8len, "buf8_len", buf8_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf8, "buf8", TRACE_SEQ_BYTE_HEX, buf8_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf82len, "buf82_len", buf82_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf82, "buf82", TRACE_SEQ_BYTE_HEX, buf82_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_HEX16, "hex16:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf16len, "buf16_len", buf16_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf16, "buf16", TRACE_SEQ_WORD_HEX, buf16_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf162len, "buf162_len", buf162_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf162, "buf162", TRACE_SEQ_WORD_HEX, buf162_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_HEX32, "hex32:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf32len, "buf32_len", buf32_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf32, "buf32", TRACE_SEQ_DWORD_HEX, buf32_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf322len, "buf322_len", buf322_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf322, "buf322", TRACE_SEQ_DWORD_HEX, buf322_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_HEX64, "hex64:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf64len, "buf64_len", buf64_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf64, "buf64", TRACE_SEQ_QWORD_HEX, buf64_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf642len, "buf642_len", buf642_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf642, "buf642", TRACE_SEQ_QWORD_HEX, buf642_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_FFIX, "ffix:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloatlen, "bufFloat_len", bufFloat_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, bufFloat_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloat2len, "bufFloat2_len", bufFloat2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat2, "bufFloat2", TRACE_SEQ_QWORD_HEX, bufFloat2_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_FEXP, "fexp:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloatlen, "bufFloat_len", bufFloat_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, bufFloat_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloat2len, "bufFloat2_len", bufFloat2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat2, "bufFloat2", TRACE_SEQ_QWORD_HEX, bufFloat2_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ARRAY_SIMILAR2_FOPT, "fopt:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloatlen, "bufFloat_len", bufFloat_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat, "bufFloat", TRACE_SEQ_QWORD_HEX, bufFloat_lenref, ISIHDR_DONT_GENERATE )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, bufFloat2len, "bufFloat2_len", bufFloat2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( bufFloat2, "bufFloat2", TRACE_SEQ_QWORD_HEX, bufFloat2_lenref, ISIHDR_DONT_GENERATE )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( ENUM_OK_TEST, "TraceCompilerTesterBasic: ENUM_OK_TEST: ", ON )
		
		TRACE_BEGIN( TEST_ENUM_OK, "Enum:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE_CONST( ret, "ret", TErrorCodes )
		TRACE_END()
		
		TRACE_BEGIN( TEST_ENUM_ARRAY_OK, "Enum Array:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( buf, "buf", TErrorCodes_Seq, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( TRACE_PERFORMANCE, "TraceCompilerTesterBasic: Performance: ", ON )
		
		TRACE_BEGIN( EVENT_MY_EVENT_TRACE1_START, "Event1>" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
		TRACE_END()
		
		TRACE_BEGIN( EVENT_MY_EVENT_TRACE1_STOP, "Event1<" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
		TRACE_END()
		
		TRACE_BEGIN( EVENT_MY_EVENT_TRACE2_START, "Event2>" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
		TRACE_END()
		
		TRACE_BEGIN( EVENT_MY_EVENT_TRACE2_STOP, "Event2<" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg1, "arg1", DEC )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( TRACE_FLOW, "TraceCompilerTesterBasic: Flow: ", ON )
		
		TRACE_BEGIN( DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY, "> DTraceCompilerTesterCommon1::SumValues" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, aValue1, "aValue1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, aValue2, "aValue2", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, aValue3, "aValue3", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, aValue4, "aValue4", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, this, "this", HEX )
		TRACE_END()
		
		TRACE_BEGIN( DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT, "< DTraceCompilerTesterCommon1::SumValues" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, this, "this", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, retVal, "retVal", DEC )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( KEKKONEN, "TraceCompilerTesterBasic: KEKKONEN: ", ON )
		
		TRACE_BEGIN( TEXT1, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT2, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT3, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT4, "ifGGGGGGGGGGGGGGGGGGGGGGGLLLLLLLLLLLLj." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT5, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT6, ".iLLLGGGGGGGGGGGGGGGGGGLLLLLfffffffffjfffffjfi:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT7, ".fLLLLLGGGGGGGGGGGGGGGGLLLLLLLfffffjjjjjjjjjttjt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT8, ".iffLfLGLGGGGGGGGGGGGGGGGGLLLLfffffffjjjjjjjtttii." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT9, ".ijfffLLLLLLGGGGGGGGGGGGGGGLLLffLffffffjjjjjttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT10, "ittfffffLLLLGGGGGGGGGGGGGGGLLLLLLLffffjjjjjttttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT11, ".iitjffffLLLLLGGGGGGGGGGGGGGGGGLLLffffjjttjjtitttii" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT12, ":ittffLLLLGGGLGGGGGGGGGWGGGGGGGGLLLLffjjttjjtittiiii:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT13, ".,tjjffLLLGGGGGGGGGGGGWWWWWGGGGGGGLLLffjjtjfftitttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT14, ",jffjjffLLGGGGGGGGGWWWWGGGWWWWWWWGGLLjjtjffjtttttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT15, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT16, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT17, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT18, ". ..:,:::..  ....," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT19, "::    :,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT20, "::  .:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT21, "....:," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT22, ",:.:,,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT23, ".,,:..:," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT24, ".:..::::..ifLWDDWGLLLLj" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT25, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT26, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT27, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT28, "," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT29, ".iifjttttjfLGGLLLLLLLLffffjtfLffffjjt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT30, ",iLGi,:,,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT31, ".,jLfjtjjfLLGGGGGGGGLLLLfjjfLfjjjti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT32, "ijjjjjjttjjfffLLGGGLLLLfjjfjjjji" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT33, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT34, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT35, ".itjjjfLLLGGGWWWWGGLjji" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT36, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT37, "::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT38, ".: ........::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT39, ",j. ......:::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT40, ",fj,  .  ..,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT41, "tWLf.   ..:,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT42, "jK##EL" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT43, "LK#Effj" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT44, "EEi.     .:EKKKKKKKKL:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT45, ":DitD#KKKKKG" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT46, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT47, ".iWD  .:::::,,:fE#Dt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT48, ",L#D:ijttiiii" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT49, "jK#  ...::,,.  ." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
	
	TRACE_GROUP_END()

RES_END

#undef AUTOGEN_TRACES_HAVE_FIXED_IDS
#include <isi_macros.h>

#endif
