// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TRACECOMPILERTESTERADVANCED_20011111_TRACEDEFINITIONS_H__
#define __TRACECOMPILERTESTERADVANCED_20011111_TRACEDEFINITIONS_H__

#define AUTOGEN_TRACES_HAVE_FIXED_IDS
#include <isi_macros.h>

#undef TRACECOMPILERTESTERADVANCED_COMPONENT
#define TRACECOMPILERTESTERADVANCED_COMPONENT 0x20011111
#undef INCLUDED_NON_SOURCE_FILE_TEST
#define INCLUDED_NON_SOURCE_FILE_TEST 0xde
#undef HELLO_WORLD
#define HELLO_WORLD 0x1
#undef NON_SOURCE_FILE_TRACE1
#define NON_SOURCE_FILE_TRACE1 0x2
#undef NON_SOURCE_FILE_TRACE2
#define NON_SOURCE_FILE_TRACE2 0x3
#undef TRACE_FLOW
#define TRACE_FLOW 0x8a
#undef HELLO_MOON
#define HELLO_MOON 0x1
#undef TEST_TRACE_2
#define TEST_TRACE_2 0x2
#undef DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY
#define DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY 0x3
#undef DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT
#define DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT 0x4
#undef POINTER_PARAMETER_TEST
#define POINTER_PARAMETER_TEST 0xdf
#undef POINTER_PARAMETER_TRACE1
#define POINTER_PARAMETER_TRACE1 0x1
#undef POINTER_PARAMETER_TRACE2
#define POINTER_PARAMETER_TRACE2 0x2
#undef LONG_TRACE_TEST
#define LONG_TRACE_TEST 0xe0
#undef ASCII60
#define ASCII60 0x1
#undef ASCII300
#define ASCII300 0x2
#undef ASCII512
#define ASCII512 0x3
#undef ASCII600
#define ASCII600 0x4
#undef ASCII300_ASCII512
#define ASCII300_ASCII512 0x5
#undef ASCII600_ASCII300
#define ASCII600_ASCII300 0x6
#undef ASCII333_ASCII333
#define ASCII333_ASCII333 0x7
#undef SHORT_TRACE_TEST
#define SHORT_TRACE_TEST 0xe1
#undef ASCII1
#define ASCII1 0x1
#undef ASCII2
#define ASCII2 0x2
#undef ASCII3
#define ASCII3 0x3
#undef ASCII4
#define ASCII4 0x4
#undef ASCII5
#define ASCII5 0x5
#undef TRACE_STATE
#define TRACE_STATE 0x87
#undef STATE_TRACE_0
#define STATE_TRACE_0 0x1
#undef STATE_TRACE_1
#define STATE_TRACE_1 0x2
#undef TRACE_DATA
#define TRACE_DATA 0xe2
#undef TRACE_DATA_TRACE
#define TRACE_DATA_TRACE 0x1
#undef POST_CODE_TEST
#define POST_CODE_TEST 0xe3
#undef POST1
#define POST1 0x1
#undef KEKKONEN
#define KEKKONEN 0xe4
#undef TEXT1
#define TEXT1 0x1
#undef TEXT2
#define TEXT2 0x2
#undef TEXT3
#define TEXT3 0x3
#undef TEXT4
#define TEXT4 0x4
#undef TEXT5
#define TEXT5 0x5
#undef TEXT6
#define TEXT6 0x6
#undef TEXT7
#define TEXT7 0x7
#undef TEXT8
#define TEXT8 0x8
#undef TEXT9
#define TEXT9 0x9
#undef TEXT10
#define TEXT10 0xa
#undef TEXT11
#define TEXT11 0xb
#undef TEXT12
#define TEXT12 0xc
#undef TEXT13
#define TEXT13 0xd
#undef TEXT14
#define TEXT14 0xe
#undef TEXT15
#define TEXT15 0xf
#undef TEXT16
#define TEXT16 0x10
#undef TEXT17
#define TEXT17 0x11
#undef TEXT18
#define TEXT18 0x12
#undef TEXT19
#define TEXT19 0x13
#undef TEXT20
#define TEXT20 0x14
#undef TEXT21
#define TEXT21 0x15
#undef TEXT22
#define TEXT22 0x16
#undef TEXT23
#define TEXT23 0x17
#undef TEXT24
#define TEXT24 0x18
#undef TEXT25
#define TEXT25 0x19
#undef TEXT26
#define TEXT26 0x1a
#undef TEXT27
#define TEXT27 0x1b
#undef TEXT28
#define TEXT28 0x1c
#undef TEXT29
#define TEXT29 0x1d
#undef TEXT30
#define TEXT30 0x1e
#undef TEXT31
#define TEXT31 0x1f
#undef TEXT32
#define TEXT32 0x20
#undef TEXT33
#define TEXT33 0x21
#undef TEXT34
#define TEXT34 0x22
#undef TEXT35
#define TEXT35 0x23
#undef TEXT36
#define TEXT36 0x24
#undef TEXT37
#define TEXT37 0x25
#undef TEXT38
#define TEXT38 0x26
#undef TEXT39
#define TEXT39 0x27
#undef TEXT40
#define TEXT40 0x28
#undef TEXT41
#define TEXT41 0x29
#undef TEXT42
#define TEXT42 0x2a
#undef TEXT43
#define TEXT43 0x2b
#undef TEXT44
#define TEXT44 0x2c
#undef TEXT45
#define TEXT45 0x2d
#undef TEXT46
#define TEXT46 0x2e
#undef TEXT47
#define TEXT47 0x2f
#undef TEXT48
#define TEXT48 0x30
#undef TEXT49
#define TEXT49 0x31

RES_BEGIN( RESOURCE_TRC_SYMBIAN, TRACECOMPILERTESTERADVANCED_COMPONENT, TRACECOMPILERTESTERADVANCED_TRACE, "TRACECOMPILERTESTERADVANCED", "", FALSE )
	
	#include <SharedTraceDefinitions.h>
	
	CONST_TBL_BEGIN( MyEnum, 32, SYMBIAN_ENDIANESS, "", "" )
		CONST_TBL_ENTRY( ValueOne, 1, "" )
	CONST_TBL_END
	SEQ_BEGIN( MyEnum_Seq, DONT_CREATE_STRUCT, "", "" )
		VALUE_CONST( data, "data", MyEnum )
	SEQ_END
	
	CONST_TBL_BEGIN( x1, 32, SYMBIAN_ENDIANESS, "", "" )
		CONST_TBL_ENTRY( EVal, 1, "" )
		CONST_TBL_ENTRY( EVal2, 2, "" )
	CONST_TBL_END
	SEQ_BEGIN( x1_Seq, DONT_CREATE_STRUCT, "", "" )
		VALUE_CONST( data, "data", x1 )
	SEQ_END
	
	CONST_TBL_BEGIN( EnergyMonitor, 32, SYMBIAN_ENDIANESS, "", "" )
	CONST_TBL_END
	SEQ_BEGIN( EnergyMonitor_Seq, DONT_CREATE_STRUCT, "", "" )
		VALUE_CONST( data, "data", EnergyMonitor )
	SEQ_END
	
	TRACE_GROUP_BEGIN( INCLUDED_NON_SOURCE_FILE_TEST, "TraceCompilerTesterAdvanced: INCLUDED_NON_SOURCE_FILE_TEST: ", ON )
		
		TRACE_BEGIN( HELLO_WORLD, "Hello world!" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( NON_SOURCE_FILE_TRACE1, "Inline function GetBigValue1000 return value:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
		TRACE_END()
		
		TRACE_BEGIN( NON_SOURCE_FILE_TRACE2, "Inline function GetBigValue1000 return value:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, value, "value", DEC )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( TRACE_FLOW, "TraceCompilerTesterAdvanced: Flow: ", ON )
		
		TRACE_BEGIN( HELLO_MOON, "Hello moon!" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEST_TRACE_2, "Test OLD TraceCompiler" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( DTRACECOMPILERTESTERCOMMON1_SUMVALUES_ENTRY, "> DTraceCompilerTesterCommon1::SumValues" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, aValue1, "aValue1", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, aValue2, "aValue2", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, aValue3, "aValue3", DEC )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 8, BE, aValue4, "aValue4", DEC )
			FILLER( FILLER_FIXED, 8 )
			FILLER( FILLER_FIXED, 8 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, this, "this", HEX )
		TRACE_END()
		
		TRACE_BEGIN( DTRACECOMPILERTESTERCOMMON1_SUMVALUES_EXIT, "< DTraceCompilerTesterCommon1::SumValues" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, this, "this", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( -32, SYMBIAN_ENDIANESS, retVal, "retVal", DEC )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( POINTER_PARAMETER_TEST, "TraceCompilerTesterAdvanced: POINTER_PARAMETER_TEST: ", ON )
		
		TRACE_BEGIN( POINTER_PARAMETER_TRACE1, "Print out pointer values of two NTimers" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, myNTimer1, "myNTimer1", HEX )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, myNTimer2, "myNTimer2", HEX )
		TRACE_END()
		
		TRACE_BEGIN( POINTER_PARAMETER_TRACE2, "Print out pointer values of one const NTimers" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, myNTimer3, "myNTimer3", HEX )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( LONG_TRACE_TEST, "TraceCompilerTesterAdvanced: LONG_TRACE_TEST: ", ON )
		
		TRACE_BEGIN( ASCII60, "Ascii60:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf60, "buf60", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII300, "Ascii300:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf300, "buf300", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII512, "Ascii512:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf512, "buf512", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII600, "Ascii600:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf600, "buf600", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII300_ASCII512, "Ascii300:  Ascii512:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf300len, "buf300_len", buf300_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf300, "buf300", buf300_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf512len, "buf512_len", buf512_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf512, "buf512", buf512_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( ASCII600_ASCII300, "Ascii600:  Ascii300:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf600len, "buf600_len", buf600_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf600, "buf600", buf600_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf300len, "buf300_len", buf300_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf300, "buf300", buf300_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( ASCII333_ASCII333, "Ascii333:  Ascii333:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf333len, "buf333_len", buf333_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf333, "buf333", buf333_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf3332len, "buf3332_len", buf3332_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf3332, "buf3332", buf3332_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( SHORT_TRACE_TEST, "TraceCompilerTesterAdvanced: SHORT_TRACE_TEST: ", ON )
		
		TRACE_BEGIN( ASCII1, "Ascii1:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf1, "buf1", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII2, "Ascii2:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf2, "buf2", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII3, "Ascii3:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf3, "buf3", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII4, "Ascii4:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII_ZERO_TERMINATED, BE, buf4, "buf4", REF_LENGTH_DETERMINED_BY_ZERO, ISIHDR_DONT_GENERATE )
		TRACE_END()
		
		TRACE_BEGIN( ASCII5, "Ascii1:  Ascii2:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf1len, "buf1_len", buf1_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf1, "buf1", buf1_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, buf2len, "buf2_len", buf2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, buf2, "buf2", buf2_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( TRACE_STATE, "TraceCompilerTesterAdvanced: State: ", ON )
		
		TRACE_BEGIN( STATE_TRACE_0, "Machine;State" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, arg1len, "arg1_len", arg1_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, arg1, "arg1", arg1_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, arg2len, "arg2_len", arg2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, arg2, "arg2", arg2_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
		TRACE_END()
		
		TRACE_BEGIN( STATE_TRACE_1, "Machine;State;Instance" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, arg1len, "arg1_len", arg1_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, arg1, "arg1", arg1_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_IS_NOT_PARAMETER )
			REFERENCE( 32, SYMBIAN_ENDIANESS, arg2len, "arg2_len", arg2_lenref )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			STRING_REF( STRING_ASCII, BE, arg2, "arg2", arg2_lenref, ISIHDR_DONT_GENERATE )
			FILLER( FILLER_VARIABLE, 32 )
			PROPERTY( PROPERTY_PMD_PARAMETER )
			VALUE( 32, SYMBIAN_ENDIANESS, arg3, "arg3", HEX )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( TRACE_DATA, "TraceCompilerTesterAdvanced: Data: ", ON )
		
		TRACE_BEGIN( TRACE_DATA_TRACE, "DTraceCoreXtiIf::DebugPrintMsg - Msg via XTI IF 0x" )
			AUTOGEN_BTRACE_HEADER_MAPPED
			PROPERTY( PROPERTY_PMD_PARAMETER )
			SEQ_OF_REF( arg1, "arg1", TRACE_SEQ_BYTE_HEX, REF_AS_MANY_AS_POSSIBLE, ISIHDR_DONT_GENERATE )
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( POST_CODE_TEST, "TraceCompilerTesterAdvanced: POST_CODE_TEST: ", ON )
		
		TRACE_BEGIN( POST1, "Print some POST code traces" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
	
	TRACE_GROUP_END()
	
	TRACE_GROUP_BEGIN( KEKKONEN, "TraceCompilerTesterAdvanced: KEKKONEN: ", ON )
		
		TRACE_BEGIN( TEXT1, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT2, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT3, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT4, "ifGGGGGGGGGGGGGGGGGGGGGGGLLLLLLLLLLLLj." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT5, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT6, ".iLLLGGGGGGGGGGGGGGGGGGLLLLLfffffffffjfffffjfi:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT7, ".fLLLLLGGGGGGGGGGGGGGGGLLLLLLLfffffjjjjjjjjjttjt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT8, ".iffLfLGLGGGGGGGGGGGGGGGGGLLLLfffffffjjjjjjjtttii." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT9, ".ijfffLLLLLLGGGGGGGGGGGGGGGLLLffLffffffjjjjjttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT10, "ittfffffLLLLGGGGGGGGGGGGGGGLLLLLLLffffjjjjjttttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT11, ".iitjffffLLLLLGGGGGGGGGGGGGGGGGLLLffffjjttjjtitttii" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT12, ":ittffLLLLGGGLGGGGGGGGGWGGGGGGGGLLLLffjjttjjtittiiii:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT13, ".,tjjffLLLGGGGGGGGGGGGWWWWWGGGGGGGLLLffjjtjfftitttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT14, ",jffjjffLLGGGGGGGGGWWWWGGGWWWWWWWGGLLjjtjffjtttttti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT15, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT16, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT17, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT18, ". ..:,:::..  ....," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT19, "::    :,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT20, "::  .:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT21, "....:," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT22, ",:.:,,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT23, ".,,:..:," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT24, ".:..::::..ifLWDDWGLLLLj" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT25, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT26, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT27, "." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT28, "," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT29, ".iifjttttjfLGGLLLLLLLLffffjtfLffffjjt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT30, ",iLGi,:,,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT31, ".,jLfjtjjfLLGGGGGGGGLLLLfjjfLfjjjti" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT32, "ijjjjjjttjjfffLLGGGLLLLfjjfjjjji" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT33, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT34, ".:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT35, ".itjjjfLLLGGGWWWWGGLjji" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT36, ":" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT37, "::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT38, ".: ........::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT39, ",j. ......:::,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT40, ",fj,  .  ..,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT41, "tWLf.   ..:,," )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT42, "jK##EL" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT43, "LK#Effj" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT44, "EEi.     .:EKKKKKKKKL:" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT45, ":DitD#KKKKKG" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT46, "-" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT47, ".iWD  .:::::,,:fE#Dt" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT48, ",L#D:ijttiiii" )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
		
		TRACE_BEGIN( TEXT49, "jK#  ...::,,.  ." )
			AUTOGEN_BTRACE_HEADER_MAPPED
		TRACE_END()
	
	TRACE_GROUP_END()

RES_END

#undef AUTOGEN_TRACES_HAVE_FIXED_IDS
#include <isi_macros.h>

#endif
