// Created by TraceCompiler 2.2.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TRACECOREREGISTERWRITERTRACES_H__
#define __TRACECOREREGISTERWRITERTRACES_H__

#define KOstTraceComponentID 0x20031674

#define DTRACECOREREGISTERWRITER_REGISTER_ENTRY 0x840001
#define DTRACECOREREGISTERWRITER_REGISTER_EXIT 0x840002


#endif

// End of file

